config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  
  resources :members
  get 'home/index'

  root to: "home#index"
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, controllers: { 
    registrations: "registrations",
    confirmations: "confirmations",
    sessions: "milia/sessions", 
    passwords: "milia/passwords", 
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:patch, :put], as: :update_plan
end

app/views/common/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to ('<i class="fa fa-rocket"></i> ProjectManagement').html_safe, root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li>
          <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path(current_user), title: 'Edit Profile' %>
        </li>
        <% if current_user.is_admin? %>
          <li><%= link_to '<i class="fa fa-users"></i> Add Members'.html_safe, new_member_path, class: 'navbar-link' %></li>
          <li><%= link_to '<i class="fa fa-briefcase"></i> Change Plan'.html_safe, edit_plan_path, class: 'navbar-link' %></li>
        <% end %>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>